### ISSUE TITLE
Build only adding first style to JS and stoping after that.

### ISSUE THREAD

**Issue by dorthwein** [sabeurthabti/react-native-css#20] opened 2016-01-26 17:40 UTC
Given the following, the JS object will only contain "text": {color: "#FFF"} and nothing after that.

    text {
        color: $light
    }
    center {
        text-align: center;
        align-items: center;
        align-self: center;
        justify-content: center;
    }

**Comment by sabeurthabti** [comment] 2016-01-26 19:45
@dorthwein I will look into this, I am happy to accept a PR.

**Comment by sabeurthabti** [comment] 2016-02-03 11:49
@dorthwein I had a look and it seems that you're right. I am just between things right now and I will get to fixing this issue soon. I'd recommend to use css for now and not scss.

**Comment by irfaan** [comment] 2016-02-27 22:17
Still suffering from this even with this patch. Any idea why that might be?

**Comment by sabeurthabti** [comment] 2016-02-27 22:57
@davidgruebl can you shed some light on this?

**Comment by sabeurthabti** [comment] 2016-02-27 22:57
@irfaan can you provide some example?

**Comment by derektu** [comment] 2016-02-28 08:06
I have the same problem. Here is my css:

```
maincontainer {
    flex: 1;
    justify-content: center;
    align-items: center;
    background-color: #F5FCFF;
}
rootcontainer {
    flex: 1;
    font-size: 18;
}

```
and the compiled js only contains the first block (maincontainer).

**Comment by sabeurthabti** [comment] 2016-02-28 14:32
@derektu I am looking at this today, and I will improve the testing so we can cover these scenarios.

**Comment by sabeurthabti** [comment] 2016-02-28 14:57
@dorthwein @derektu @irfaan hi guys I tried to replicate this on my machine and I had no luck figuring out the issue. 

https://circleci.com/gh/sabeurthabti/react-native-css/81/ https://github.com/sabeurthabti/react-native-css/blob/master/test/rnc.test.js.

I am running:
node:5.3.0 and npm: 3.3.2.

**Comment by irfaan** [comment] 2016-02-28 16:07
Seeing the issue on node: v5.7.0, npm: 3.6.0.

Rolled back to react-native-css v1.2.18 and no longer experience the issue. Picked that version because that was what I used on a previous project. I didn't iterate through to see where the problem began.

**Comment by sabeurthabti** [comment] 2016-02-28 16:15
thank you @irfaan, I will investigate further.

**Comment by sabeurthabti** [comment] 2016-02-28 16:22
I tried with the specific version of node and all the tests are working fine. @irfaan if you have time can you clone this repo and run `npm install && npm test` and let me know what you get? or any error you get.

**Comment by derektu** [comment] 2016-02-29 00:00
I am running node 4.3.1, and after upgrade to v.1.2.27, the program goes away !!.
Thanks for your help.

**Comment by sabeurthabti** [comment] 2016-02-29 10:55
@derektu awesome glad it has been resolved for you. I will keep this ticket open.

**Comment by irfaan** [comment] 2016-03-01 03:40
@sabeurthabti Can confirm that `1.2.27` solved the problem. Thanks! Also, if you were waiting for me to confirm, thanks again!

**Comment by sabeurthabti** [comment] 2016-03-01 10:12
@irfaan yeah I was, glad it's working for you. I will close this issue now. Thank you everyone :+1:

**Closed by sabeurthabti** 2016-03-01 10:12 UTC
